#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Disable auto correct.
unsetopt correct_all
unsetopt correct


alias finder_show_hidden="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias finder_hide_hidden="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"


eval "$(direnv hook zsh)"
